sudo: false
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libgmp-dev
install:
  - git clone --depth 1 https://github.com/herumi/mcl.git $TRAVIS_BUILD_DIR/../mcl
script:
  - make -j3
  - make test DISABLE_THREAD_TEST=1
  - make test_go
  - bin/bls_c384_test.exe
